/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(show_energy.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4f9dfbabce1eac92b7e6e742b3f87835)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/energy/show_energy.h>
// pydoc.h is automatically generated in the build directory
#include <show_energy_pydoc.h>

void bind_show_energy(py::module& m)
{

    using show_energy = gr::energy::show_energy;


    py::class_<show_energy, gr::block, gr::basic_block, std::shared_ptr<show_energy>>(
        m, "show_energy", D(show_energy))

        .def(py::init(&show_energy::make), D(show_energy, make))


        ;
}
